### ISSUE TITLE
how to read like golang binary.read() with struct config?

### ISSUE THREAD

**Issue by emma-eva** [blackshirt/buffer#1]
on `GO` work like:
```
struct Config {
    abc int
    def  int
    ijk int
}

config := Config{} // fn (config Config) sss() {}
binary.read(read_file, binary.LittleEndian, config)
```
using your module how work like go, and on vlang?
Would be like this or not:
```
struct Config {
    abc int
    def  int
    ijk int
}

file := buffer.new_reader(...)
config := Config{} // fn (config Config) sss() {}
buffer.read(file, config, true)
```

i need go like read fn, Please show me example. thanks.

**Comment by blackshirt** [comment]
Sorry for late answer,  current state of this module  does not support pass Config to the constructor...and i dont think i would be a full blown reader, intended use case for this module is binary, or something like binary protocol parsing (reader).
You can extended for your use case with send pull request or just forking it.
V have support for params in struct form, see [trailing struct params](https://github.com/vlang/v/blob/master/doc/docs.md#trailing-struct-literal-arguments) on the v docs.

with proper support for trailing struct params 
```
[params]
struct Config {
    abc int
    def  int
    ijk int
}
```
and then you can extend it with the params
``` r := buffer.new_reader(b, clonfig)```or similar.

its seem you need `BufferedReader` from io in std vlib io

**Comment by emma-eva** [comment]
> Sorry for late answer, current state of this module does not support pass Config to the constructor...and i dont think i would be a full blown reader, intended use case for this module is binary, or something like binary protocol parsing (reader). You can extended for your use case with send pull request or just forking it. V have support for params in struct form, see [trailing struct params](https://github.com/vlang/v/blob/master/doc/docs.md#trailing-struct-literal-arguments) on the v docs.
> 
> with proper support for trailing struct params
> 
> ```
> [params]
> struct Config {
>     abc int
>     def  int
>     ijk int
> }
> ```
> 
> and then you can extend it with the params ` r := buffer.new_reader(b, clonfig)`or similar.
> 
> its seem you need `BufferedReader` from io in std vlib io

Can be do like this?
```
struct Config {
    endian bool
}

struct Reader {
	// read only buffer of underlying data being wrapped
	buf []u8
	// default to big endian read
	//endian bool = true
        // added config here
        config Config
mut:
	// current index (offset)
	idx i64
}

pub fn new_reader(b []u8, config Config) &Reader {
	return new_reader_with_endianess(b, config, true)
}

// new_reader_with_endianess create new reader.
pub fn new_reader_with_endianess(b []u8, config Config, endian bool) &Reader {
	return &Reader{
		buf: b
		idx: i64(0)
                config: config // added here
                //endian: endian
	}
}
//...
fn (mut r Reader) read_u16() !u16 {
    if r.remainder() < u16size {
        return error('not enough bytes to read on')
    }
    b, _ := r.read_sized(u16size)!
    if r.config.endian {
        return binary.big_endian_u16(b)
    }
    return binary.little_endian_u16(b)
}
//....
```

**Comment by blackshirt** [comment]
> > Sorry for late answer, current state of this module does not support pass Config to the constructor...and i dont think i would be a full blown reader, intended use case for this module is binary, or something like binary protocol parsing (reader). You can extended for your use case with send pull request or just forking it. V have support for params in struct form, see [trailing struct params](https://github.com/vlang/v/blob/master/doc/docs.md#trailing-struct-literal-arguments) on the v docs.
> > with proper support for trailing struct params
> > ```
> > [params]
> > struct Config {
> >     abc int
> >     def  int
> >     ijk int
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then you can extend it with the params ` r := buffer.new_reader(b, clonfig)`or similar.
> > its seem you need `BufferedReader` from io in std vlib io
> 
> Can be do like this?
> 
> ```
> struct Config {
>     endian bool
> }
> 
> struct Reader {
> 	// read only buffer of underlying data being wrapped
> 	buf []u8
> 	// default to big endian read
> 	//endian bool = true
>         // added config here
>         config Config
> mut:
> 	// current index (offset)
> 	idx i64
> }
> 
> pub fn new_reader(b []u8, config Config) &Reader {
> 	return new_reader_with_endianess(b, config, true)
> }
> 
> // new_reader_with_endianess create new reader.
> pub fn new_reader_with_endianess(b []u8, config Config, endian bool) &Reader {
> 	return &Reader{
> 		buf: b
> 		idx: i64(0)
>                 config: config // added here
>                 //endian: endian
> 	}
> }
> //...
> fn (mut r Reader) read_u16() !u16 {
>     if r.remainder() < u16size {
>         return error('not enough bytes to read on')
>     }
>     b, _ := r.read_sized(u16size)!
>     if r.config.endian {
>         return binary.big_endian_u16(b)
>     }
>     return binary.little_endian_u16(b)
> }
> //....
> ```

sure,  you can extend it...see `fn new_buffered_reader()` from `vlib.io` module ..its accept `BufferedReaderConfig` struct
